POSTGRES_USERNAME=udagrambtdev
POSTGRES_PASSWORD=udagrambtdev
POSTGRES_DB=udagrambtdev
POSTGRES_HOST=udagrambtdev.cvnytmcypfhy.us-east-1.rds.amazonaws.com

AWS_BUCKET=udacity-project-ms
URL=http://udagram-users-app-svc:8080

JWT_SECRET=helloworld